// Sdílený seznam tabulek a bucketů pro zálohu/obnovu (client-safe konstanty).
export const BACKUP_TABLES = [
  "profiles",
  "user_roles",
  "user_modules",
  "attendance_absences",
  "attendance_employees",
  "attendance_employee_pins",
  "attendance_notifications",
  "attendance_pin_ip_allowlist",
  "attendance_records",
  "attendance_settings",
  "attendance_shifts",
  "audit_log",
  "backup_settings",
  "backup_runs",
  "claim_attachments",
  "claim_events",
  "claim_tasks",
  "claims",
  "clients",
  "deal_stage_history",
  "deals",
  "defects",
  "deletion_requests",
  "demo_order_documents",
  "demo_order_events",
  "demo_order_signatures",
  "demo_orders",
  "document_templates",
  "email_send_log",
  "email_send_state",
  "email_unsubscribe_tokens",
  "evidence_orders",
  "evidence_wash_assignments",
  "logbook_entries",
  "logbook_vehicles",
  "pin_attempt_log",
  "purchases",
  "suppliers",
  "suppressed_emails",
  "task_attachments",
  "task_comments",
  "tasks",
  "vykup_photos",
  "vykupy",
  "washers",
] as const;

export const BACKUP_BUCKETS = [
  "attendance-reports",
  "defect-photos",
  "logbook-receipts",
  "slides",
  "vykup-photos",
  "task-attachments",
  "claim-files",
] as const;

/** Buckety, které se na Disk zrcadlí 1:1 (soubor po souboru do složek). */
export const MIRRORED_BUCKETS = [
  "defect-photos",
  "logbook-receipts",
  "slides",
  "vykup-photos",
  "task-attachments",
  "claim-files",
] as const;
