/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NahlasitRouteImport } from './routes/nahlasit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadTokenRouteImport } from './routes/upload.$token'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedVykupyIndexRouteImport } from './routes/_authenticated/vykupy/index'
import { Route as AuthenticatedDochazkaIndexRouteImport } from './routes/_authenticated/dochazka/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedVykupyDashboardRouteImport } from './routes/_authenticated/vykupy/dashboard'
import { Route as AuthenticatedVykupyIdRouteImport } from './routes/_authenticated/vykupy/$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin/templates'
import { Route as AuthenticatedAdminIdRouteImport } from './routes/_authenticated/admin/$id'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NahlasitRoute = NahlasitRouteImport.update({
  id: '/nahlasit',
  path: '/nahlasit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadTokenRoute = UploadTokenRouteImport.update({
  id: '/upload/$token',
  path: '/upload/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVykupyIndexRoute =
  AuthenticatedVykupyIndexRouteImport.update({
    id: '/vykupy/',
    path: '/vykupy/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDochazkaIndexRoute =
  AuthenticatedDochazkaIndexRouteImport.update({
    id: '/dochazka/',
    path: '/dochazka/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVykupyDashboardRoute =
  AuthenticatedVykupyDashboardRouteImport.update({
    id: '/vykupy/dashboard',
    path: '/vykupy/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVykupyIdRoute = AuthenticatedVykupyIdRouteImport.update({
  id: '/vykupy/$id',
  path: '/vykupy/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/admin/templates',
    path: '/admin/templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIdRoute = AuthenticatedAdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nahlasit': typeof NahlasitRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminal': typeof TerminalRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/upload/$token': typeof UploadTokenRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/vykupy/$id': typeof AuthenticatedVykupyIdRoute
  '/vykupy/dashboard': typeof AuthenticatedVykupyDashboardRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dochazka/': typeof AuthenticatedDochazkaIndexRoute
  '/vykupy/': typeof AuthenticatedVykupyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nahlasit': typeof NahlasitRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminal': typeof TerminalRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/upload/$token': typeof UploadTokenRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/vykupy/$id': typeof AuthenticatedVykupyIdRoute
  '/vykupy/dashboard': typeof AuthenticatedVykupyDashboardRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dochazka': typeof AuthenticatedDochazkaIndexRoute
  '/vykupy': typeof AuthenticatedVykupyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/nahlasit': typeof NahlasitRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminal': typeof TerminalRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/upload/$token': typeof UploadTokenRoute
  '/_authenticated/admin/$id': typeof AuthenticatedAdminIdRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/vykupy/$id': typeof AuthenticatedVykupyIdRoute
  '/_authenticated/vykupy/dashboard': typeof AuthenticatedVykupyDashboardRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dochazka/': typeof AuthenticatedDochazkaIndexRoute
  '/_authenticated/vykupy/': typeof AuthenticatedVykupyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/nahlasit'
    | '/reset-password'
    | '/terminal'
    | '/approvals'
    | '/dashboard'
    | '/upload/$token'
    | '/admin/$id'
    | '/admin/templates'
    | '/admin/users'
    | '/vykupy/$id'
    | '/vykupy/dashboard'
    | '/admin/'
    | '/dochazka/'
    | '/vykupy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/nahlasit'
    | '/reset-password'
    | '/terminal'
    | '/approvals'
    | '/dashboard'
    | '/upload/$token'
    | '/admin/$id'
    | '/admin/templates'
    | '/admin/users'
    | '/vykupy/$id'
    | '/vykupy/dashboard'
    | '/admin'
    | '/dochazka'
    | '/vykupy'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/nahlasit'
    | '/reset-password'
    | '/terminal'
    | '/_authenticated/approvals'
    | '/_authenticated/dashboard'
    | '/upload/$token'
    | '/_authenticated/admin/$id'
    | '/_authenticated/admin/templates'
    | '/_authenticated/admin/users'
    | '/_authenticated/vykupy/$id'
    | '/_authenticated/vykupy/dashboard'
    | '/_authenticated/admin/'
    | '/_authenticated/dochazka/'
    | '/_authenticated/vykupy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NahlasitRoute: typeof NahlasitRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TerminalRoute: typeof TerminalRoute
  UploadTokenRoute: typeof UploadTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nahlasit': {
      id: '/nahlasit'
      path: '/nahlasit'
      fullPath: '/nahlasit'
      preLoaderRoute: typeof NahlasitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$token': {
      id: '/upload/$token'
      path: '/upload/$token'
      fullPath: '/upload/$token'
      preLoaderRoute: typeof UploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vykupy/': {
      id: '/_authenticated/vykupy/'
      path: '/vykupy'
      fullPath: '/vykupy/'
      preLoaderRoute: typeof AuthenticatedVykupyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dochazka/': {
      id: '/_authenticated/dochazka/'
      path: '/dochazka'
      fullPath: '/dochazka/'
      preLoaderRoute: typeof AuthenticatedDochazkaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vykupy/dashboard': {
      id: '/_authenticated/vykupy/dashboard'
      path: '/vykupy/dashboard'
      fullPath: '/vykupy/dashboard'
      preLoaderRoute: typeof AuthenticatedVykupyDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vykupy/$id': {
      id: '/_authenticated/vykupy/$id'
      path: '/vykupy/$id'
      fullPath: '/vykupy/$id'
      preLoaderRoute: typeof AuthenticatedVykupyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$id': {
      id: '/_authenticated/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminIdRoute: typeof AuthenticatedAdminIdRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedVykupyIdRoute: typeof AuthenticatedVykupyIdRoute
  AuthenticatedVykupyDashboardRoute: typeof AuthenticatedVykupyDashboardRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedDochazkaIndexRoute: typeof AuthenticatedDochazkaIndexRoute
  AuthenticatedVykupyIndexRoute: typeof AuthenticatedVykupyIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminIdRoute: AuthenticatedAdminIdRoute,
  AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedVykupyIdRoute: AuthenticatedVykupyIdRoute,
  AuthenticatedVykupyDashboardRoute: AuthenticatedVykupyDashboardRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedDochazkaIndexRoute: AuthenticatedDochazkaIndexRoute,
  AuthenticatedVykupyIndexRoute: AuthenticatedVykupyIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  NahlasitRoute: NahlasitRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TerminalRoute: TerminalRoute,
  UploadTokenRoute: UploadTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
