/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvdisplayRouteImport } from './routes/tvdisplay'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NahlasitRouteImport } from './routes/nahlasit'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TVdisplayRouteImport } from './routes/TVdisplay'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadTokenRouteImport } from './routes/upload.$token'
import { Route as TvTokenRouteImport } from './routes/tv.$token'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as FeedbackTokenRouteImport } from './routes/feedback.$token'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedZavadyIndexRouteImport } from './routes/_authenticated/zavady/index'
import { Route as AuthenticatedVykupyIndexRouteImport } from './routes/_authenticated/vykupy/index'
import { Route as AuthenticatedUkolyIndexRouteImport } from './routes/_authenticated/ukoly/index'
import { Route as AuthenticatedLogbookIndexRouteImport } from './routes/_authenticated/logbook/index'
import { Route as AuthenticatedEvidenceZakazekIndexRouteImport } from './routes/_authenticated/evidence-zakazek/index'
import { Route as AuthenticatedDochazkaIndexRouteImport } from './routes/_authenticated/dochazka/index'
import { Route as AuthenticatedDemoOrdersIndexRouteImport } from './routes/_authenticated/demo-orders/index'
import { Route as AuthenticatedDealsIndexRouteImport } from './routes/_authenticated/deals/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as WashRespondActionTokenRouteImport } from './routes/wash-respond.$action.$token'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedVykupyDashboardRouteImport } from './routes/_authenticated/vykupy/dashboard'
import { Route as AuthenticatedVykupyIdRouteImport } from './routes/_authenticated/vykupy/$id'
import { Route as AuthenticatedDemoOrdersIdRouteImport } from './routes/_authenticated/demo-orders/$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTvRouteImport } from './routes/_authenticated/admin/tv'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin/templates'
import { Route as AuthenticatedAdminStorageRouteImport } from './routes/_authenticated/admin/storage'
import { Route as AuthenticatedAdminGoogleDriveRouteImport } from './routes/_authenticated/admin/google-drive'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminIdRouteImport } from './routes/_authenticated/admin/$id'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksWeeklyReportRouteImport } from './routes/api/public/hooks/weekly-report'
import { Route as ApiPublicHooksWashRemindersRouteImport } from './routes/api/public/hooks/wash-reminders'
import { Route as ApiPublicCronTaskRemindersRouteImport } from './routes/api/public/cron/task-reminders'
import { Route as ApiPublicCronTaskDailyDigestRouteImport } from './routes/api/public/cron/task-daily-digest'
import { Route as ApiPublicCronGithubSnapshotRouteImport } from './routes/api/public/cron/github-snapshot'
import { Route as ApiPublicCronFollowupRemindersRouteImport } from './routes/api/public/cron/followup-reminders'
import { Route as ApiPublicCronBackupRouteImport } from './routes/api/public/cron/backup'

const TvdisplayRoute = TvdisplayRouteImport.update({
  id: '/tvdisplay',
  path: '/tvdisplay',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NahlasitRoute = NahlasitRouteImport.update({
  id: '/nahlasit',
  path: '/nahlasit',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TVdisplayRoute = TVdisplayRouteImport.update({
  id: '/TVdisplay',
  path: '/TVdisplay',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadTokenRoute = UploadTokenRouteImport.update({
  id: '/upload/$token',
  path: '/upload/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TvTokenRoute = TvTokenRouteImport.update({
  id: '/tv/$token',
  path: '/tv/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackTokenRoute = FeedbackTokenRouteImport.update({
  id: '/feedback/$token',
  path: '/feedback/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZavadyIndexRoute =
  AuthenticatedZavadyIndexRouteImport.update({
    id: '/zavady/',
    path: '/zavady/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVykupyIndexRoute =
  AuthenticatedVykupyIndexRouteImport.update({
    id: '/vykupy/',
    path: '/vykupy/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUkolyIndexRoute = AuthenticatedUkolyIndexRouteImport.update({
  id: '/ukoly/',
  path: '/ukoly/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogbookIndexRoute =
  AuthenticatedLogbookIndexRouteImport.update({
    id: '/logbook/',
    path: '/logbook/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvidenceZakazekIndexRoute =
  AuthenticatedEvidenceZakazekIndexRouteImport.update({
    id: '/evidence-zakazek/',
    path: '/evidence-zakazek/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDochazkaIndexRoute =
  AuthenticatedDochazkaIndexRouteImport.update({
    id: '/dochazka/',
    path: '/dochazka/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoOrdersIndexRoute =
  AuthenticatedDemoOrdersIndexRouteImport.update({
    id: '/demo-orders/',
    path: '/demo-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDealsIndexRoute = AuthenticatedDealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const WashRespondActionTokenRoute = WashRespondActionTokenRouteImport.update({
  id: '/wash-respond/$action/$token',
  path: '/wash-respond/$action/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVykupyDashboardRoute =
  AuthenticatedVykupyDashboardRouteImport.update({
    id: '/vykupy/dashboard',
    path: '/vykupy/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVykupyIdRoute = AuthenticatedVykupyIdRouteImport.update({
  id: '/vykupy/$id',
  path: '/vykupy/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemoOrdersIdRoute =
  AuthenticatedDemoOrdersIdRouteImport.update({
    id: '/demo-orders/$id',
    path: '/demo-orders/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTvRoute = AuthenticatedAdminTvRouteImport.update({
  id: '/admin/tv',
  path: '/admin/tv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/admin/templates',
    path: '/admin/templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStorageRoute =
  AuthenticatedAdminStorageRouteImport.update({
    id: '/admin/storage',
    path: '/admin/storage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGoogleDriveRoute =
  AuthenticatedAdminGoogleDriveRouteImport.update({
    id: '/admin/google-drive',
    path: '/admin/google-drive',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIdRoute = AuthenticatedAdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWeeklyReportRoute =
  ApiPublicHooksWeeklyReportRouteImport.update({
    id: '/api/public/hooks/weekly-report',
    path: '/api/public/hooks/weekly-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWashRemindersRoute =
  ApiPublicHooksWashRemindersRouteImport.update({
    id: '/api/public/hooks/wash-reminders',
    path: '/api/public/hooks/wash-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronTaskRemindersRoute =
  ApiPublicCronTaskRemindersRouteImport.update({
    id: '/api/public/cron/task-reminders',
    path: '/api/public/cron/task-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronTaskDailyDigestRoute =
  ApiPublicCronTaskDailyDigestRouteImport.update({
    id: '/api/public/cron/task-daily-digest',
    path: '/api/public/cron/task-daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronGithubSnapshotRoute =
  ApiPublicCronGithubSnapshotRouteImport.update({
    id: '/api/public/cron/github-snapshot',
    path: '/api/public/cron/github-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronFollowupRemindersRoute =
  ApiPublicCronFollowupRemindersRouteImport.update({
    id: '/api/public/cron/followup-reminders',
    path: '/api/public/cron/followup-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronBackupRoute = ApiPublicCronBackupRouteImport.update({
  id: '/api/public/cron/backup',
  path: '/api/public/cron/backup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/TVdisplay': typeof TVdisplayRoute
  '/auth': typeof AuthRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/nahlasit': typeof NahlasitRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminal': typeof TerminalRoute
  '/tvdisplay': typeof TvdisplayRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/feedback/$token': typeof FeedbackTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/tv/$token': typeof TvTokenRoute
  '/upload/$token': typeof UploadTokenRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/google-drive': typeof AuthenticatedAdminGoogleDriveRoute
  '/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/tv': typeof AuthenticatedAdminTvRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/demo-orders/$id': typeof AuthenticatedDemoOrdersIdRoute
  '/vykupy/$id': typeof AuthenticatedVykupyIdRoute
  '/vykupy/dashboard': typeof AuthenticatedVykupyDashboardRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/wash-respond/$action/$token': typeof WashRespondActionTokenRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/deals/': typeof AuthenticatedDealsIndexRoute
  '/demo-orders/': typeof AuthenticatedDemoOrdersIndexRoute
  '/dochazka/': typeof AuthenticatedDochazkaIndexRoute
  '/evidence-zakazek/': typeof AuthenticatedEvidenceZakazekIndexRoute
  '/logbook/': typeof AuthenticatedLogbookIndexRoute
  '/ukoly/': typeof AuthenticatedUkolyIndexRoute
  '/vykupy/': typeof AuthenticatedVykupyIndexRoute
  '/zavady/': typeof AuthenticatedZavadyIndexRoute
  '/api/public/cron/backup': typeof ApiPublicCronBackupRoute
  '/api/public/cron/followup-reminders': typeof ApiPublicCronFollowupRemindersRoute
  '/api/public/cron/github-snapshot': typeof ApiPublicCronGithubSnapshotRoute
  '/api/public/cron/task-daily-digest': typeof ApiPublicCronTaskDailyDigestRoute
  '/api/public/cron/task-reminders': typeof ApiPublicCronTaskRemindersRoute
  '/api/public/hooks/wash-reminders': typeof ApiPublicHooksWashRemindersRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/TVdisplay': typeof TVdisplayRoute
  '/auth': typeof AuthRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/nahlasit': typeof NahlasitRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminal': typeof TerminalRoute
  '/tvdisplay': typeof TvdisplayRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/feedback/$token': typeof FeedbackTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/tv/$token': typeof TvTokenRoute
  '/upload/$token': typeof UploadTokenRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/google-drive': typeof AuthenticatedAdminGoogleDriveRoute
  '/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/tv': typeof AuthenticatedAdminTvRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/demo-orders/$id': typeof AuthenticatedDemoOrdersIdRoute
  '/vykupy/$id': typeof AuthenticatedVykupyIdRoute
  '/vykupy/dashboard': typeof AuthenticatedVykupyDashboardRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/wash-respond/$action/$token': typeof WashRespondActionTokenRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/deals': typeof AuthenticatedDealsIndexRoute
  '/demo-orders': typeof AuthenticatedDemoOrdersIndexRoute
  '/dochazka': typeof AuthenticatedDochazkaIndexRoute
  '/evidence-zakazek': typeof AuthenticatedEvidenceZakazekIndexRoute
  '/logbook': typeof AuthenticatedLogbookIndexRoute
  '/ukoly': typeof AuthenticatedUkolyIndexRoute
  '/vykupy': typeof AuthenticatedVykupyIndexRoute
  '/zavady': typeof AuthenticatedZavadyIndexRoute
  '/api/public/cron/backup': typeof ApiPublicCronBackupRoute
  '/api/public/cron/followup-reminders': typeof ApiPublicCronFollowupRemindersRoute
  '/api/public/cron/github-snapshot': typeof ApiPublicCronGithubSnapshotRoute
  '/api/public/cron/task-daily-digest': typeof ApiPublicCronTaskDailyDigestRoute
  '/api/public/cron/task-reminders': typeof ApiPublicCronTaskRemindersRoute
  '/api/public/hooks/wash-reminders': typeof ApiPublicHooksWashRemindersRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/TVdisplay': typeof TVdisplayRoute
  '/auth': typeof AuthRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/nahlasit': typeof NahlasitRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminal': typeof TerminalRoute
  '/tvdisplay': typeof TvdisplayRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/feedback/$token': typeof FeedbackTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/tv/$token': typeof TvTokenRoute
  '/upload/$token': typeof UploadTokenRoute
  '/_authenticated/admin/$id': typeof AuthenticatedAdminIdRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/google-drive': typeof AuthenticatedAdminGoogleDriveRoute
  '/_authenticated/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/admin/tv': typeof AuthenticatedAdminTvRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/demo-orders/$id': typeof AuthenticatedDemoOrdersIdRoute
  '/_authenticated/vykupy/$id': typeof AuthenticatedVykupyIdRoute
  '/_authenticated/vykupy/dashboard': typeof AuthenticatedVykupyDashboardRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/wash-respond/$action/$token': typeof WashRespondActionTokenRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/deals/': typeof AuthenticatedDealsIndexRoute
  '/_authenticated/demo-orders/': typeof AuthenticatedDemoOrdersIndexRoute
  '/_authenticated/dochazka/': typeof AuthenticatedDochazkaIndexRoute
  '/_authenticated/evidence-zakazek/': typeof AuthenticatedEvidenceZakazekIndexRoute
  '/_authenticated/logbook/': typeof AuthenticatedLogbookIndexRoute
  '/_authenticated/ukoly/': typeof AuthenticatedUkolyIndexRoute
  '/_authenticated/vykupy/': typeof AuthenticatedVykupyIndexRoute
  '/_authenticated/zavady/': typeof AuthenticatedZavadyIndexRoute
  '/api/public/cron/backup': typeof ApiPublicCronBackupRoute
  '/api/public/cron/followup-reminders': typeof ApiPublicCronFollowupRemindersRoute
  '/api/public/cron/github-snapshot': typeof ApiPublicCronGithubSnapshotRoute
  '/api/public/cron/task-daily-digest': typeof ApiPublicCronTaskDailyDigestRoute
  '/api/public/cron/task-reminders': typeof ApiPublicCronTaskRemindersRoute
  '/api/public/hooks/wash-reminders': typeof ApiPublicHooksWashRemindersRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/TVdisplay'
    | '/auth'
    | '/manifest.webmanifest'
    | '/nahlasit'
    | '/reset-password'
    | '/terminal'
    | '/tvdisplay'
    | '/approvals'
    | '/dashboard'
    | '/email/unsubscribe'
    | '/feedback/$token'
    | '/sign/$token'
    | '/tv/$token'
    | '/upload/$token'
    | '/admin/$id'
    | '/admin/audit'
    | '/admin/google-drive'
    | '/admin/storage'
    | '/admin/templates'
    | '/admin/tv'
    | '/admin/users'
    | '/demo-orders/$id'
    | '/vykupy/$id'
    | '/vykupy/dashboard'
    | '/lovable/email/suppression'
    | '/wash-respond/$action/$token'
    | '/admin/'
    | '/deals/'
    | '/demo-orders/'
    | '/dochazka/'
    | '/evidence-zakazek/'
    | '/logbook/'
    | '/ukoly/'
    | '/vykupy/'
    | '/zavady/'
    | '/api/public/cron/backup'
    | '/api/public/cron/followup-reminders'
    | '/api/public/cron/github-snapshot'
    | '/api/public/cron/task-daily-digest'
    | '/api/public/cron/task-reminders'
    | '/api/public/hooks/wash-reminders'
    | '/api/public/hooks/weekly-report'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/TVdisplay'
    | '/auth'
    | '/manifest.webmanifest'
    | '/nahlasit'
    | '/reset-password'
    | '/terminal'
    | '/tvdisplay'
    | '/approvals'
    | '/dashboard'
    | '/email/unsubscribe'
    | '/feedback/$token'
    | '/sign/$token'
    | '/tv/$token'
    | '/upload/$token'
    | '/admin/$id'
    | '/admin/audit'
    | '/admin/google-drive'
    | '/admin/storage'
    | '/admin/templates'
    | '/admin/tv'
    | '/admin/users'
    | '/demo-orders/$id'
    | '/vykupy/$id'
    | '/vykupy/dashboard'
    | '/lovable/email/suppression'
    | '/wash-respond/$action/$token'
    | '/admin'
    | '/deals'
    | '/demo-orders'
    | '/dochazka'
    | '/evidence-zakazek'
    | '/logbook'
    | '/ukoly'
    | '/vykupy'
    | '/zavady'
    | '/api/public/cron/backup'
    | '/api/public/cron/followup-reminders'
    | '/api/public/cron/github-snapshot'
    | '/api/public/cron/task-daily-digest'
    | '/api/public/cron/task-reminders'
    | '/api/public/hooks/wash-reminders'
    | '/api/public/hooks/weekly-report'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/TVdisplay'
    | '/auth'
    | '/manifest.webmanifest'
    | '/nahlasit'
    | '/reset-password'
    | '/terminal'
    | '/tvdisplay'
    | '/_authenticated/approvals'
    | '/_authenticated/dashboard'
    | '/email/unsubscribe'
    | '/feedback/$token'
    | '/sign/$token'
    | '/tv/$token'
    | '/upload/$token'
    | '/_authenticated/admin/$id'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/google-drive'
    | '/_authenticated/admin/storage'
    | '/_authenticated/admin/templates'
    | '/_authenticated/admin/tv'
    | '/_authenticated/admin/users'
    | '/_authenticated/demo-orders/$id'
    | '/_authenticated/vykupy/$id'
    | '/_authenticated/vykupy/dashboard'
    | '/lovable/email/suppression'
    | '/wash-respond/$action/$token'
    | '/_authenticated/admin/'
    | '/_authenticated/deals/'
    | '/_authenticated/demo-orders/'
    | '/_authenticated/dochazka/'
    | '/_authenticated/evidence-zakazek/'
    | '/_authenticated/logbook/'
    | '/_authenticated/ukoly/'
    | '/_authenticated/vykupy/'
    | '/_authenticated/zavady/'
    | '/api/public/cron/backup'
    | '/api/public/cron/followup-reminders'
    | '/api/public/cron/github-snapshot'
    | '/api/public/cron/task-daily-digest'
    | '/api/public/cron/task-reminders'
    | '/api/public/hooks/wash-reminders'
    | '/api/public/hooks/weekly-report'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  TVdisplayRoute: typeof TVdisplayRoute
  AuthRoute: typeof AuthRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  NahlasitRoute: typeof NahlasitRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TerminalRoute: typeof TerminalRoute
  TvdisplayRoute: typeof TvdisplayRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  FeedbackTokenRoute: typeof FeedbackTokenRoute
  SignTokenRoute: typeof SignTokenRoute
  TvTokenRoute: typeof TvTokenRoute
  UploadTokenRoute: typeof UploadTokenRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  WashRespondActionTokenRoute: typeof WashRespondActionTokenRoute
  ApiPublicCronBackupRoute: typeof ApiPublicCronBackupRoute
  ApiPublicCronFollowupRemindersRoute: typeof ApiPublicCronFollowupRemindersRoute
  ApiPublicCronGithubSnapshotRoute: typeof ApiPublicCronGithubSnapshotRoute
  ApiPublicCronTaskDailyDigestRoute: typeof ApiPublicCronTaskDailyDigestRoute
  ApiPublicCronTaskRemindersRoute: typeof ApiPublicCronTaskRemindersRoute
  ApiPublicHooksWashRemindersRoute: typeof ApiPublicHooksWashRemindersRoute
  ApiPublicHooksWeeklyReportRoute: typeof ApiPublicHooksWeeklyReportRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tvdisplay': {
      id: '/tvdisplay'
      path: '/tvdisplay'
      fullPath: '/tvdisplay'
      preLoaderRoute: typeof TvdisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nahlasit': {
      id: '/nahlasit'
      path: '/nahlasit'
      fullPath: '/nahlasit'
      preLoaderRoute: typeof NahlasitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TVdisplay': {
      id: '/TVdisplay'
      path: '/TVdisplay'
      fullPath: '/TVdisplay'
      preLoaderRoute: typeof TVdisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$token': {
      id: '/upload/$token'
      path: '/upload/$token'
      fullPath: '/upload/$token'
      preLoaderRoute: typeof UploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$token': {
      id: '/tv/$token'
      path: '/tv/$token'
      fullPath: '/tv/$token'
      preLoaderRoute: typeof TvTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$token': {
      id: '/feedback/$token'
      path: '/feedback/$token'
      fullPath: '/feedback/$token'
      preLoaderRoute: typeof FeedbackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zavady/': {
      id: '/_authenticated/zavady/'
      path: '/zavady'
      fullPath: '/zavady/'
      preLoaderRoute: typeof AuthenticatedZavadyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vykupy/': {
      id: '/_authenticated/vykupy/'
      path: '/vykupy'
      fullPath: '/vykupy/'
      preLoaderRoute: typeof AuthenticatedVykupyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ukoly/': {
      id: '/_authenticated/ukoly/'
      path: '/ukoly'
      fullPath: '/ukoly/'
      preLoaderRoute: typeof AuthenticatedUkolyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logbook/': {
      id: '/_authenticated/logbook/'
      path: '/logbook'
      fullPath: '/logbook/'
      preLoaderRoute: typeof AuthenticatedLogbookIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evidence-zakazek/': {
      id: '/_authenticated/evidence-zakazek/'
      path: '/evidence-zakazek'
      fullPath: '/evidence-zakazek/'
      preLoaderRoute: typeof AuthenticatedEvidenceZakazekIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dochazka/': {
      id: '/_authenticated/dochazka/'
      path: '/dochazka'
      fullPath: '/dochazka/'
      preLoaderRoute: typeof AuthenticatedDochazkaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo-orders/': {
      id: '/_authenticated/demo-orders/'
      path: '/demo-orders'
      fullPath: '/demo-orders/'
      preLoaderRoute: typeof AuthenticatedDemoOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals/': {
      id: '/_authenticated/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof AuthenticatedDealsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/wash-respond/$action/$token': {
      id: '/wash-respond/$action/$token'
      path: '/wash-respond/$action/$token'
      fullPath: '/wash-respond/$action/$token'
      preLoaderRoute: typeof WashRespondActionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vykupy/dashboard': {
      id: '/_authenticated/vykupy/dashboard'
      path: '/vykupy/dashboard'
      fullPath: '/vykupy/dashboard'
      preLoaderRoute: typeof AuthenticatedVykupyDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vykupy/$id': {
      id: '/_authenticated/vykupy/$id'
      path: '/vykupy/$id'
      fullPath: '/vykupy/$id'
      preLoaderRoute: typeof AuthenticatedVykupyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo-orders/$id': {
      id: '/_authenticated/demo-orders/$id'
      path: '/demo-orders/$id'
      fullPath: '/demo-orders/$id'
      preLoaderRoute: typeof AuthenticatedDemoOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tv': {
      id: '/_authenticated/admin/tv'
      path: '/admin/tv'
      fullPath: '/admin/tv'
      preLoaderRoute: typeof AuthenticatedAdminTvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/storage': {
      id: '/_authenticated/admin/storage'
      path: '/admin/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AuthenticatedAdminStorageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/google-drive': {
      id: '/_authenticated/admin/google-drive'
      path: '/admin/google-drive'
      fullPath: '/admin/google-drive'
      preLoaderRoute: typeof AuthenticatedAdminGoogleDriveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$id': {
      id: '/_authenticated/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-report': {
      id: '/api/public/hooks/weekly-report'
      path: '/api/public/hooks/weekly-report'
      fullPath: '/api/public/hooks/weekly-report'
      preLoaderRoute: typeof ApiPublicHooksWeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/wash-reminders': {
      id: '/api/public/hooks/wash-reminders'
      path: '/api/public/hooks/wash-reminders'
      fullPath: '/api/public/hooks/wash-reminders'
      preLoaderRoute: typeof ApiPublicHooksWashRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/task-reminders': {
      id: '/api/public/cron/task-reminders'
      path: '/api/public/cron/task-reminders'
      fullPath: '/api/public/cron/task-reminders'
      preLoaderRoute: typeof ApiPublicCronTaskRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/task-daily-digest': {
      id: '/api/public/cron/task-daily-digest'
      path: '/api/public/cron/task-daily-digest'
      fullPath: '/api/public/cron/task-daily-digest'
      preLoaderRoute: typeof ApiPublicCronTaskDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/github-snapshot': {
      id: '/api/public/cron/github-snapshot'
      path: '/api/public/cron/github-snapshot'
      fullPath: '/api/public/cron/github-snapshot'
      preLoaderRoute: typeof ApiPublicCronGithubSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/followup-reminders': {
      id: '/api/public/cron/followup-reminders'
      path: '/api/public/cron/followup-reminders'
      fullPath: '/api/public/cron/followup-reminders'
      preLoaderRoute: typeof ApiPublicCronFollowupRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/backup': {
      id: '/api/public/cron/backup'
      path: '/api/public/cron/backup'
      fullPath: '/api/public/cron/backup'
      preLoaderRoute: typeof ApiPublicCronBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminIdRoute: typeof AuthenticatedAdminIdRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminGoogleDriveRoute: typeof AuthenticatedAdminGoogleDriveRoute
  AuthenticatedAdminStorageRoute: typeof AuthenticatedAdminStorageRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminTvRoute: typeof AuthenticatedAdminTvRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedDemoOrdersIdRoute: typeof AuthenticatedDemoOrdersIdRoute
  AuthenticatedVykupyIdRoute: typeof AuthenticatedVykupyIdRoute
  AuthenticatedVykupyDashboardRoute: typeof AuthenticatedVykupyDashboardRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedDealsIndexRoute: typeof AuthenticatedDealsIndexRoute
  AuthenticatedDemoOrdersIndexRoute: typeof AuthenticatedDemoOrdersIndexRoute
  AuthenticatedDochazkaIndexRoute: typeof AuthenticatedDochazkaIndexRoute
  AuthenticatedEvidenceZakazekIndexRoute: typeof AuthenticatedEvidenceZakazekIndexRoute
  AuthenticatedLogbookIndexRoute: typeof AuthenticatedLogbookIndexRoute
  AuthenticatedUkolyIndexRoute: typeof AuthenticatedUkolyIndexRoute
  AuthenticatedVykupyIndexRoute: typeof AuthenticatedVykupyIndexRoute
  AuthenticatedZavadyIndexRoute: typeof AuthenticatedZavadyIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminIdRoute: AuthenticatedAdminIdRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminGoogleDriveRoute: AuthenticatedAdminGoogleDriveRoute,
  AuthenticatedAdminStorageRoute: AuthenticatedAdminStorageRoute,
  AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
  AuthenticatedAdminTvRoute: AuthenticatedAdminTvRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedDemoOrdersIdRoute: AuthenticatedDemoOrdersIdRoute,
  AuthenticatedVykupyIdRoute: AuthenticatedVykupyIdRoute,
  AuthenticatedVykupyDashboardRoute: AuthenticatedVykupyDashboardRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedDealsIndexRoute: AuthenticatedDealsIndexRoute,
  AuthenticatedDemoOrdersIndexRoute: AuthenticatedDemoOrdersIndexRoute,
  AuthenticatedDochazkaIndexRoute: AuthenticatedDochazkaIndexRoute,
  AuthenticatedEvidenceZakazekIndexRoute:
    AuthenticatedEvidenceZakazekIndexRoute,
  AuthenticatedLogbookIndexRoute: AuthenticatedLogbookIndexRoute,
  AuthenticatedUkolyIndexRoute: AuthenticatedUkolyIndexRoute,
  AuthenticatedVykupyIndexRoute: AuthenticatedVykupyIndexRoute,
  AuthenticatedZavadyIndexRoute: AuthenticatedZavadyIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  TVdisplayRoute: TVdisplayRoute,
  AuthRoute: AuthRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  NahlasitRoute: NahlasitRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TerminalRoute: TerminalRoute,
  TvdisplayRoute: TvdisplayRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  FeedbackTokenRoute: FeedbackTokenRoute,
  SignTokenRoute: SignTokenRoute,
  TvTokenRoute: TvTokenRoute,
  UploadTokenRoute: UploadTokenRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  WashRespondActionTokenRoute: WashRespondActionTokenRoute,
  ApiPublicCronBackupRoute: ApiPublicCronBackupRoute,
  ApiPublicCronFollowupRemindersRoute: ApiPublicCronFollowupRemindersRoute,
  ApiPublicCronGithubSnapshotRoute: ApiPublicCronGithubSnapshotRoute,
  ApiPublicCronTaskDailyDigestRoute: ApiPublicCronTaskDailyDigestRoute,
  ApiPublicCronTaskRemindersRoute: ApiPublicCronTaskRemindersRoute,
  ApiPublicHooksWashRemindersRoute: ApiPublicHooksWashRemindersRoute,
  ApiPublicHooksWeeklyReportRoute: ApiPublicHooksWeeklyReportRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
