REVOKE EXECUTE ON FUNCTION public.enqueue_email(text, jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.read_email_batch(text, integer, integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.delete_email(text, bigint) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.move_to_dlq(text, text, bigint, jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.email_queue_dispatch() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.email_queue_wake() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.next_demo_invoice_number() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.assign_demo_order_number() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.assign_pu_number() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.deals_log_stage_history() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.deals_track_stage_change() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_attendance_absences_approval() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_attendance_records_approval() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_deletion_requests_approval() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_purchases_approval() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_suppliers_approval() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.log_claim_created() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.set_created_by_default() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.touch_updated_at() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.vykupy_track_stav_change() FROM anon, authenticated;